### ISSUE TITLE
Toggle Chat bar

### ISSUE THREAD

**Issue by yhw99go** [bestlkh/ice-MC2#105]
Toggle the chat bar in Desktop Version

**Comment by junthehacker** [comment]
I noticed that the bar displays on mobile for some reason:
![image](https://user-images.githubusercontent.com/7855724/34925377-f522449a-f976-11e7-8808-e0a191360ac1.png)
Also the resize seems now not working.

**Comment by junthehacker** [comment]
Just found a minor bug.
![2018-01-25 21 30 51](https://user-images.githubusercontent.com/7855724/35422516-1f448910-0217-11e8-836f-b4a1f6b8bb7d.gif)

**Comment by hughdani** [comment]
will look into this

**Comment by yhw99go** [comment]
It's working fine at first loading
but it's happening when we refresh the page

**Comment by hughdani** [comment]
it is caused by the dragbar overflowing because the editor has taken up all the space (the #editorframe has width: 100%)
