### ISSUE TITLE
Refactor/document svgcanvas.js

### ISSUE THREAD

**Issue by hughdani** [bestlkh/ice-MC2#112]

**Comment by junthehacker** [comment]
@hughdani 
Do you think we can just use a UML chart for this?
I currently use StarUML which has unlimited trial time. We can have the whole system documented in there.

The stuff I sent you few days ago was generated by StarUML.

**Comment by hughdani** [comment]
@junthehacker 
In my experience, I have not encountered heavily documented code because most of it was for internal purposes with a small team and comments in the source code was sufficient. I think It depends on who we are writing this documentation for. I don't mind using UML diagrams because it is a clear way for technical users to learn how the project works. I liked how you had API styled documentation for your functions because it allows for easier reuse of code and I think we should require this as a minimum for the code we write moving forward. UML diagrams are usually done before coding so it would already be there as part of documentation. For code that was created externally I am not sure what to do. We could start with UML diagrams as it would help with visualizing how everything is related, however it doesn't seem right that we document code that was retrieved externally. For files like svgcanvas.js in particular, we should separate our code from vendor code and document what we have written while noting where it calls vendor functions.
