### ISSUE TITLE
Chat message being sent multiple times

### ISSUE THREAD

**Issue by Gazing** [bestlkh/ice-MC2#148]
When sending a message in the chat if you spam the send button, it will cause the same message to be sent multiple times.

**Comment by junthehacker** [comment]
I am unable to reproduce this bug.
This is the code that controls the message sending, I am unable to reproduce this bug regardless how fast I spam the send button.
https://github.com/bestlkh/ice-MC2/blob/issue-148/public/app/controllers/chatRoomController.js#L269

**Comment by Gazing** [comment]
Appears to have disappeared.
This was tested both on local(master) and mc2.

Closing issue
