### ISSUE TITLE
Typing "∞" (type i multiple times) gives the following error (probably more characters like this)

### ISSUE THREAD

**Issue by bestlkh** [bestlkh/ice-MC2#161]
Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.

**Comment by Gazing** [comment]
Specifically happens when using the convert tool.

**Comment by hughdani** [comment]
Sigma symbol causes a related issue

![image](https://user-images.githubusercontent.com/31714259/36011566-4366d81a-0d26-11e8-9bc7-1db7593af914.png)

**Comment by bestlkh** [comment]
it should be fixed if input method changes completely #119
