### ISSUE TITLE
Login Initials

### ISSUE THREAD

**Issue by hughdani** [bestlkh/ice-MC2#164]
When changed it remains the default two letters of the username in the chat.

**Comment by junthehacker** [comment]
Do you guys think it will make sense if we take user name exploded by space, then take `arr[0][0].uppercase` and `arr[len(arr) - 1][0].uppercase` as initials?
If there is no space, we can just take the first two and uppercase it.
@YueGan @hughdani @Gazing @yhw99go

**Comment by hughdani** [comment]
My concern was that it just gave the user an illusion of choice since it didn't really allow them to change it since it defaulted.

**Comment by yhw99go** [comment]
I don't think it really matter. 
but I checked that skype takes first two letters if there is no space.
and first letters if there is space

**Comment by junthehacker** [comment]
Ok, I think we can prob just make the initials a label then, instead of an editable textbox.
