### ISSUE TITLE
Remove Button Visible After Resizing Chat

### ISSUE THREAD

**Issue by hughdani** [bestlkh/ice-MC2#167]
![image](https://user-images.githubusercontent.com/31714259/35368583-f47aeed8-0151-11e8-85f8-8f5cfa92aeb2.png)

**Comment by junthehacker** [comment]
I think this is due to how we handled responsiveness.
Some code work dynamically (does not require page reload), some code only detects size on startup.
I think we need to streamline our approach on responsiveness.
Maybe media query + `onResize` binding works?
