### ISSUE TITLE
Resize Button Position

### ISSUE THREAD

**Issue by hughdani** [bestlkh/ice-MC2#169]
(desktop) When the app is started the button is initially on the left menu toolbar.

![image](https://user-images.githubusercontent.com/31714259/35368872-95aa2584-0153-11e8-835c-102f6ad80d21.png)

**Comment by yhw99go** [comment]
is that showing at very first time?

**Comment by hughdani** [comment]
yes

**Comment by hughdani** [comment]
@yhw99go problem seems to go away in the most recent master branch locally

**Comment by yhw99go** [comment]
sounds good I will move to close
