### ISSUE TITLE
Physical Keyboard Bindings

### ISSUE THREAD

**Issue by hughdani** [bestlkh/ice-MC2#216]
(Chrome Desktop) Combining Shift and '=' produces the '+/-'  symbol rather than the expected '+' symbol.

(Firefox Desktop) Pressing the '=/+' symbol on the physical keyboard in the main area (not the key on the number-pad) produces the '+' symbol rather than the expected '=' symbol. Pressing the '-' symbol on the physical keyboard in the main area does not produce any symbols (no binds?).

**Comment by Gazing** [comment]
caused by a duplicate key handler

**Comment by hughdani** [comment]
The Firefox issue still exists @Gazing :

(Firefox Desktop) Pressing the '=/+' symbol on the physical keyboard in the main area (not the key on the number-pad) produces the '+' symbol rather than the expected '=' symbol. Pressing the '-' symbol on the physical keyboard in the main area does not produce any symbols (no binds?).
