### ISSUE TITLE
getBST Console Error

### ISSUE THREAD

**Issue by hughdani** [bestlkh/ice-MC2#217]
(Emulated mobile size screen) clicking the convert and send airplane icon and then either send as equation or send as image results in this: 

"test" seems to be the default text.

![image](https://user-images.githubusercontent.com/31714259/35831688-a01b70b0-0a98-11e8-81e5-f19895ad2dee.png)

![image](https://user-images.githubusercontent.com/31714259/35831556-173acab6-0a98-11e8-8a2a-5af90f12b949.png)

**Comment by bestlkh** [comment]
is this still happening?

**Comment by junthehacker** [comment]
I have fixed this, moving to done.
