### ISSUE TITLE
Instructor Creation

### ISSUE THREAD

**Issue by hughdani** [bestlkh/ice-MC2#251]
Can instructors only be created internally through AdminView/register.js or is there an interface for it? Going to /register/ shows this:

![image](https://user-images.githubusercontent.com/31714259/35999655-92f95232-0cee-11e8-971e-df161841ed58.png)

![image](https://user-images.githubusercontent.com/31714259/35999649-8dcb37a8-0cee-11e8-9399-06c90efc448b.png)

**Comment by Gazing** [comment]
only internally. I think that might some remnant of a previous prototype for lecture chats.
