### ISSUE TITLE
Convert to Equation Containing Brackets

### ISSUE THREAD

**Issue by hughdani** [bestlkh/ice-MC2#288]
- From a fresh canvas, clicking '(' from the Math tab using the popup keyboard makes clicking ')'  unresponsive. Also you are not able to highlight anything afterwards unless you click/move the '('.

- Sometimes the recognition is wrong resulting in bad latex format.

![image](https://user-images.githubusercontent.com/31714259/36109478-8c69ba0e-0fed-11e8-968c-0e348f609f97.png)

![image](https://user-images.githubusercontent.com/31714259/36109524-ab2de7bc-0fed-11e8-898c-ea68c57c69d7.png)

![image](https://user-images.githubusercontent.com/31714259/36109616-eae7c1e8-0fed-11e8-8764-1633b5ce4a31.png)

**Comment by junthehacker** [comment]
@hughdani 
i think this issue only applies if you use the SVG type of brackets.
a center issue, closing bracket gets recognized in the SUPER region of i.
should be fixed later.

But if you type brackets with keyboard now, everything should work.

**Comment by hughdani** [comment]
Correct, typing brackets on a physical keyboard works. SVG symbols are sketchy as it is supposed to programmatically wrap the expression perfectly but doesn't. 

As a test, try and reproduce this expression using the built in keyboard while using SVG symbols when possible. If you can do this with minimal rearrangement, then the detection algorithm should be robust.
![image](https://user-images.githubusercontent.com/31714259/37677673-163ba4ce-2c52-11e8-8f86-7e00fe667193.png)


This is still happening: 
> - From a fresh canvas, clicking '(' from the Math tab using the popup keyboard makes clicking ')' unresponsive. Also you are not able to highlight anything afterwards unless you click/move the '('.

Btw, the first two images recognize the incomplete expression correctly and I am not sure if we can do anything about it if its how LaTeX works.

**Comment by junthehacker** [comment]
Makes no sense to fix this before we have the SVG refactored.
