### ISSUE TITLE
Enable Rotation

### ISSUE THREAD

**Issue by hughdani** [bestlkh/ice-MC2#351]
Marco previously commented out rotation on images. Enable the feature.

**Comment by junthehacker** [comment]
Hopefully we can find it lol.

Sent from my iPhone

On Mar 21, 2018, at 4:44 PM, Daniel Hugh <notifications@github.com<mailto:notifications@github.com>> wrote:


Marco previously commented out rotation on images. Enable the feature.

**Comment by hughdani** [comment]
@junthehacker at ice.html #tools_top contains a menu for #tool_angle. It wasn't commented out but display: none. There is a UI but some looks like it needs to be rewired.
